<script setup>
import launcher from "../../../../desktop/package.json";
const { enabled: desktop } = useDesktop();
useSeo({ title: 'Windows launcher', description: 'Download the Ranked World launcher for Windows. See your rank and recent rounds, join Gorilla Tag ranked codes from your PC, and manage your account.' });
const features = [{ name: 'Your rank and recent rounds', icon: 'activity' }, { name: 'Join codes from the launcher', icon: 'play' }, { name: 'Party, practice and account controls', icon: 'users' }, { name: 'Signed launcher updates', icon: 'download' }];
</script>
<template>
<DesktopSettings v-if="desktop" /><main v-else id="main" class="wrap section"><div class="world-page-title"><h1>Launcher</h1><span class="chip">Windows</span></div><section class="world-launcher-intro"><span class="world-launcher-mark"><img src="/img/planet.png" alt="Ranked World" /></span><div><h2>Ranked World</h2><p class="meta">Your stats, account and ranked codes in one desktop app.</p><div class="world-practice-start"><a class="btn btn--brand" :href="`/downloads/launcher/${launcher.version}/RankedWorld-Setup.exe`" download>Download for Windows<AppIcon name="download" /></a></div><p class="meta">Version {{ launcher.version }} / Windows 10 or later, 64 bit</p></div></section><section class="world-launcher-roadmap"><div v-for="feature in features" :key="feature.name" class="world-setting-row"><AppIcon :name="feature.icon" /><h3>{{ feature.name }}</h3></div></section><section class="world-panel" style="margin-top:24px;padding:24px"><h2>Joining from your PC</h2><p class="meta">You need the Steam version of Gorilla Tag and BepInEx. The launcher asks before installing JoinHelper.dll into BepInEx/plugins/RankedDeps. Close the game for installation, then join a code from the launcher. If the helper is already loaded, you can join while the game is running.</p><p class="meta">Standalone Quest players can still enter codes inside Gorilla Tag.</p></section></main>
</template>
