<script setup>
useHead({title:"Notifications | Ranked World"});
const {me}=useMe(),{state,unread,refresh,markRead}=useNotifications(),{enabled:desktop,signIn,loginPending}=useDesktop(),{toast}=useToast();
const busy=ref(false);
async function read(ids){busy.value=true;try{await markRead(ids)}catch(e){toast(e.message,"bad")}finally{busy.value=false}}
async function open(n){if(!n.readAt)await read([n.id]);await navigateTo(n.to)}
const status=n=>({accepted:"Accepted",declined:"Declined",unavailable:"No longer available"}[n.status]||"");
const date=value=>new Date(value).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
onMounted(refresh);
</script>
<template>
<main id="main" class="wrap section"><div class="world-page-title"><div><h1>Notifications <span v-if="unread" class="chip">{{ unread }} unread</span></h1></div><button v-if="unread" class="btn" :disabled="busy" @click="read()">Mark all as read</button></div><section v-if="!me.user" class="slab notification-empty"><AppIcon name="bell" /><h2>Sign in to see your notifications</h2><button v-if="desktop" class="btn btn--brand" :disabled="loginPending" @click="signIn">Sign in</button><NuxtLink v-else class="btn btn--brand" to="/sign-in">Sign in</NuxtLink></section><div v-else-if="state.error" class="world-error" role="alert"><p>{{ state.error }}</p><button class="btn" @click="refresh">Try again</button></div><p v-else-if="!state.loaded" role="status" class="meta">Loading notifications...</p><section v-else-if="!state.items.length" class="slab notification-empty"><AppIcon name="bell" /><h2>No notifications yet</h2><p class="meta">Your match, membership, and account updates will appear here.</p></section><div v-else class="notification-list"><article v-for="n in state.items" :key="n.id" class="notification-item" :class="{'notification-item--unread':!n.readAt}"><PlayerAvatar :contain="n.kind !== 'party_invite'" :name="n.actorName" :src="n.avatar" :size="42" /><div class="notification-copy"><div class="notification-title"><h2>{{ n.title }}</h2><span v-if="!n.readAt" class="notification-dot" aria-label="Unread" /></div><p>{{ n.body }}</p><time :datetime="n.createdAt">{{ date(n.createdAt) }}</time><span v-if="status(n)" class="chip">{{ status(n) }}</span><div class="notification-actions"><button v-if="n.to" class="btn btn--brand" :disabled="busy" @click="open(n)">{{ n.kind === 'party_invite' ? 'Open invitation' : 'View details' }}</button><button v-if="!n.readAt" class="btn btn--ghost" :disabled="busy" @click="read([n.id])">Mark as read</button></div></div></article><p class="meta notification-retention">Showing your latest 50 notifications. Notifications stay here for 30 days.</p></div></main>
</template>
<style scoped>
.notification-list{max-width:850px;display:grid;gap:10px}.notification-item{display:flex;gap:16px;padding:22px;border:1px solid var(--color-divider);border-radius:12px;background:var(--surface-2)}.notification-item--unread{border-left:3px solid var(--color-brand);padding-left:20px}.notification-copy{min-width:0;flex:1}.notification-title{display:flex;align-items:center;gap:10px}.notification-title h2{font-size:16px;margin:0}.notification-copy p{margin:6px 0;overflow-wrap:anywhere}.notification-copy time{font-size:12px;color:var(--color-text-secondary);margin-right:12px}.notification-dot{width:7px;height:7px;border-radius:50%;background:var(--color-brand)}.notification-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.notification-empty{max-width:850px;padding:48px 24px;display:grid;justify-items:center;gap:16px;text-align:center}.notification-empty>svg{width:30px;height:30px;color:var(--color-text-secondary)}.notification-empty h2{font-size:18px}.notification-retention{font-size:12px;margin-top:8px}@media(max-width:600px){.notification-item{padding:16px;gap:12px}.notification-item--unread{padding-left:14px}.notification-actions .btn{font-size:12px}}
</style>
