<script setup>
import { RANKED_SLOTS } from '@ranked-world/ranks';
const { me } = useMe(), { signIn, loginPending } = useDesktop();
const { data, pending, error, refresh } = await useApiFetch('/api/me/player', { key: 'launcher-player', default: () => ({ player: null }) });
const { data: rooms, pending: loadingCodes, error: codeError, refresh: refreshCodes } = await useApiFetch('/api/codes', { key: 'launcher-codes', default: () => ({ codes: [] }) });
const player = computed(() => data.value?.player), linked = computed(() => Boolean(player.value?.linked));
const mode = ref('ranked'), track = computed(() => player.value?.[mode.value]), tier = computed(() => track.value?.tier);
const codes = computed(() => (rooms.value?.codes || []).filter(c => c.active)), rounds = computed(() => (player.value?.matches || []).slice(0, 4));
const stat = n => num(n), progress = computed(() => tier.value?.isTop ? 100 : Math.max(0, Math.min(100, tier.value?.percent || 0)));
let poll;
onMounted(() => { poll = setInterval(() => { refresh(); refreshCodes(); }, 15000); });
onBeforeUnmount(() => clearInterval(poll));
useHead({ title: 'My stats | Ranked World' });
</script>
<template>
<main id="main" class="wrap section launcher-home"><header class="launcher-title"><div><h1>My stats</h1><p v-if="linked" class="meta">{{ player.name || me.user?.username }}</p></div><div v-if="linked" class="launcher-tabs" aria-label="Stats track"><button v-for="key in ['ranked', 'scrim']" :key="key" :aria-pressed="mode === key" @click="mode = key">{{ key === 'ranked' ? 'Ranked' : 'Scrims' }}</button></div></header>
<div class="launcher-grid"><div class="launcher-main"><section v-if="error" class="launcher-panel launcher-empty" role="alert"><h2>Stats unavailable</h2><button class="btn" @click="refresh">Try again</button></section><section v-else-if="pending" class="launcher-panel launcher-empty" aria-busy="true" role="status">Loading your stats...</section><section v-else-if="!linked" class="launcher-panel launcher-welcome"><img src="/img/planet.png" alt="" /><h2>{{ me.user ? 'Connect Gorilla Tag' : 'Your stats start here' }}</h2><p class="meta">{{ me.user ? 'Connect your game account to see your rank and available codes.' : 'Sign in to see your rank, recent matches, and ranked codes.' }}</p><NuxtLink v-if="me.user" to="/play" class="btn btn--brand">Connect game account</NuxtLink><button v-else class="btn btn--brand" :disabled="loginPending" @click="signIn">Sign in</button></section><section v-else class="launcher-panel launcher-rating"><div class="launcher-rank"><RankBadge v-if="tier" :tier="tier" :size="112" :show-percent="false" /><div><h2>{{ tier?.name || 'No rank yet' }}</h2><p class="launcher-elo">{{ stat(track?.elo) }}<span>Elo</span></p><p v-if="tier" class="meta">{{ tier.category }} bracket</p></div></div><div v-if="tier" class="launcher-progress"><div role="progressbar" :aria-valuenow="progress" aria-valuemin="0" aria-valuemax="100" aria-label="Progress to next division"><span :style="{ width: progress + '%' }" /></div><span>{{ tier.isTop ? 'Top division' : tier.eloToNext == null ? 'Rank progress' : tier.eloToNext + ' Elo to next division' }}</span></div><dl class="launcher-metrics"><div><dt>Win rate</dt><dd>{{ track?.winRate == null ? '0%' : track.winRate + '%' }}</dd></div><div><dt>Rounds played</dt><dd>{{ stat(track?.rounds) }}</dd></div><div><dt>Personal best</dt><dd>{{ stat(track?.peakElo) }}</dd></div></dl></section>
<section class="launcher-panel launcher-recent"><div class="launcher-panel-head"><h2>Recent rounds</h2><NuxtLink to="/history">History<AppIcon name="arrowRight" /></NuxtLink></div><div v-if="rounds.length" class="launcher-rounds"><div v-for="(round, i) in rounds" :key="round.roundId || i"><span class="launcher-place">{{ round.placement == null ? 'N/A' : '#' + (round.placement + 1) }}</span><span><strong>{{ round.code || 'Ranked round' }}</strong><small>{{ round.at || round.createdAt ? ago(round.at || round.createdAt) : round.track === 'scrim' ? 'Scrim' : 'Ranked' }}</small></span><span class="launcher-delta" :class="round.delta >= 0 ? 'pos' : 'neg'">{{ round.delta == null ? 'Unknown' : (round.delta >= 0 ? '+' : '') + round.delta }}<small>Elo</small></span></div></div><p v-else class="launcher-note">{{ linked ? 'Your recent rounds will appear here.' : 'Connect your game account to see match history.' }}</p></section></div>
<aside class="launcher-panel launcher-codes"><div class="launcher-panel-head"><h2>Join a code</h2><span v-if="codes.length" class="chip">{{ codes.length }} open</span></div><p v-if="loadingCodes" class="launcher-note" role="status">Loading codes...</p><div v-else-if="codeError" class="launcher-empty" role="alert"><p>Codes are unavailable.</p><button class="btn" @click="refreshCodes">Retry codes</button></div><template v-else-if="codes.length"><div v-for="code in codes.slice(0, 3)" :key="code.code" class="launcher-room"><div><strong>{{ code.code }}</strong><small>{{ code.count ?? 0 }}/{{ RANKED_SLOTS }} players / {{ code.category || rooms.bracket }}</small></div><RoomJoinButton :code="code.code" /></div></template><div v-else class="launcher-empty"><AppIcon name="hash" /><h3>{{ linked ? 'No open codes' : 'Connect your account' }}</h3><p class="meta">{{ linked ? 'Try practice or check again shortly.' : 'Your ranked codes will appear here once your game account is connected.' }}</p></div><NuxtLink to="/play" class="btn launcher-all-codes">{{ linked ? 'All play modes' : 'Open Play' }}<AppIcon name="arrowRight" /></NuxtLink></aside></div>
<section class="launcher-manage" aria-label="Manage your account and sessions"><NuxtLink to="/play?mode=scrims"><AppIcon name="users" /><span>Party<small>Invites and scrims</small></span><AppIcon name="arrowRight" /></NuxtLink><NuxtLink to="/play?mode=practice"><AppIcon name="target" /><span>Practice<small>Bot sessions</small></span><AppIcon name="arrowRight" /></NuxtLink><NuxtLink to="/settings"><AppIcon name="settings" /><span>Account<small>Connections and membership</small></span><AppIcon name="arrowRight" /></NuxtLink></section>
</main>
</template>
