<script setup lang="ts">
const route = useRoute();
const { update, showUpdate, enabled, available, status, busy, pendingJoin, requestLaunch, failure, login, loginPending, action, cancelSignIn } = useDesktop();
</script>
<template>
<div v-if="enabled" class="desktop-bar"><div class="desktop-bar__game"><img src="/img/planet.png" alt="" width="34" height="25" /><div><strong>Gorilla Tag</strong><span>{{ status?.gameRunning ? 'Running' : status?.gameInstalled ? 'Ready to launch' : 'Set up your game' }}</span></div></div><div class="desktop-bar__actions"><button v-if="update.available" class="btn desktop-update-badge" :disabled="busy" @click="showUpdate()"><AppIcon name="download" />Update available</button><NuxtLink class="btn btn--ghost" to="/launcher"><AppIcon name="settings" />Game settings</NuxtLink><button v-if="route.path !== '/'" class="btn btn--brand" :disabled="!available || busy || !status?.gameInstalled || status?.gameRunning || pendingJoin" @click="requestLaunch()"><AppIcon name="play" />{{ status?.gameRunning ? 'Game running' : 'Launch Gorilla Tag' }}</button></div><div v-if="status?.join" class="desktop-bar__notice" role="status"><span>{{ status.join.code ? status.join.code + ': ' : '' }}{{ status.join.message }}</span><button v-if="pendingJoin" class="btn btn--ghost" :disabled="busy" @click="action('cancel_join')">Cancel join</button></div><div v-if="loginPending && login" class="desktop-bar__notice" role="status"><span>Approve code <strong>{{ login.userCode }}</strong> in your browser to sign in.</span><button class="btn btn--ghost" @click="cancelSignIn">Cancel sign-in</button></div><div v-if="failure" class="desktop-bar__notice bad" role="alert"><span>{{ failure }}</span><button class="btn btn--ghost" aria-label="Dismiss launcher error" @click="failure = ''">Dismiss</button></div></div>
</template>
<style scoped>
</style>
