<script setup lang="ts">
const { prompt, requestedCode, update, updateRequired, progress, promptError, status, busy, acceptPrompt, cancelPrompt } = useDesktop();
const dialog = ref<HTMLDialogElement | null>(null);
let previousFocus: HTMLElement | null = null;
const blocked = computed(() => prompt.value === 'helper' && (status.value?.gameRunning || !status.value?.bepInExInstalled));
const title = computed(() => prompt.value === 'update' ? progress.value ? progress.value.phase === 'installing' ? 'Installing update' : 'Downloading update' : updateRequired.value ? 'Update required' : 'Launcher update' : status.value?.gameRunning ? 'Close Gorilla Tag first' : 'Download the join helper');
const percent = computed(() => progress.value?.total ? Math.min(100, Math.round(progress.value.downloaded / progress.value.total * 100)) : undefined);
watch(prompt, async value => { await nextTick(); if (value && dialog.value && !dialog.value.open) { previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null; dialog.value.showModal(); } else if (!value && dialog.value?.open) { dialog.value.close(); previousFocus?.focus(); previousFocus = null; } }, { flush: 'post' });
function trap(event: KeyboardEvent) { if (event.key !== 'Tab' || !dialog.value) return; const controls = Array.from(dialog.value.querySelectorAll<HTMLElement>('button:not(:disabled), [href], input:not(:disabled), [tabindex="0"]')); if (!controls.length) { event.preventDefault(); dialog.value.focus(); return; } const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && (document.activeElement === first || document.activeElement === dialog.value)) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }
function escape(event: Event) { event.preventDefault(); cancelPrompt(); }
onBeforeUnmount(() => { dialog.value?.close(); previousFocus?.focus(); });
</script>
<template>
<Teleport to="body"><dialog ref="dialog" class="desktop-prompt" aria-labelledby="desktop-prompt-title" aria-describedby="desktop-prompt-description" :aria-busy="busy || !!progress" @cancel="escape" @keydown="trap" tabindex="-1"><img class="desktop-prompt__logo" src="/img/planet.png" alt="Ranked World" /><h2 id="desktop-prompt-title">{{ title }}</h2><div id="desktop-prompt-description"><template v-if="prompt === 'update'"><p v-if="progress">{{ progress.phase === 'installing' ? 'The launcher will restart when installation finishes.' : 'Downloading the latest launcher. Keep this window open.' }}</p><p v-else>{{ updateRequired ? 'Update your launcher before launching or joining a room.' : 'A new launcher version is ready to download.' }}{{ update.version ? ` Version ${update.version}.` : '' }}</p></template><template v-else><p v-if="status?.gameRunning">Close Gorilla Tag, then download the helper to join {{ requestedCode }}. The game must restart to load it.</p><p v-else-if="!status?.bepInExInstalled">Install BepInEx in your Gorilla Tag folder, then try joining again.</p><p v-else>Download the helper into your Gorilla Tag plugins folder, then join {{ requestedCode }}. The helper sends your selected room code to the game.</p></template></div><div v-if="progress" class="desktop-prompt__progress" role="status" aria-live="polite"><progress max="100" :value="percent" :aria-label="title" /><span>{{ progress.phase === 'installing' ? 'Installing and restarting...' : percent === undefined ? 'Starting download...' : `${percent}% downloaded` }}</span></div><p v-if="promptError" class="bad" role="alert">{{ promptError }}</p><div v-if="!progress" class="desktop-prompt__actions"><button class="btn" :disabled="busy" autofocus @click="cancelPrompt">Cancel</button><button v-if="!blocked" class="btn btn--brand" :disabled="busy" @click="acceptPrompt">{{ busy ? 'Downloading helper...' : prompt === 'update' ? 'Update now' : 'Download helper' }}</button></div></dialog></Teleport>
</template>
